"""initial schema

Revision ID: 0f8b1e62be0a
Revises: 
Create Date: 2026-07-28 15:33:12.103203
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0f8b1e62be0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_species',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scientific_name', sa.String(length=200), nullable=False),
    sa.Column('common_name', sa.String(length=200), nullable=True),
    sa.Column('genus', sa.String(length=100), nullable=True),
    sa.Column('plant_id_ref', sa.String(length=64), nullable=True),
    sa.Column('care_profile', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plant_species', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plant_species_genus'), ['genus'], unique=False)
        batch_op.create_index(batch_op.f('ix_plant_species_plant_id_ref'), ['plant_id_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_plant_species_scientific_name'), ['scientific_name'], unique=False)

    op.create_table('readings',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('rh', sa.Float(), nullable=True),
    sa.Column('soil_pct', sa.Float(), nullable=True),
    sa.Column('lux', sa.Float(), nullable=True),
    sa.Column('batt_mv', sa.Integer(), nullable=True),
    sa.Column('flags', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('time', 'device_id')
    )
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.create_index('ix_readings_device_time', ['device_id', 'time'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_firebase_uid'), ['firebase_uid'], unique=True)

    op.create_table('devices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('hw_serial', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=32), nullable=False),
    sa.Column('fw_version', sa.String(length=32), nullable=True),
    sa.Column('mqtt_secret_hash', sa.String(length=255), nullable=True),
    sa.Column('claim_code', sa.String(length=32), nullable=True),
    sa.Column('claim_code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_by', sa.String(length=36), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claimed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_claim_code'), ['claim_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_claimed_by'), ['claimed_by'], unique=False)

    op.create_table('commands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('op', sa.String(length=32), nullable=False),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('issued_by', sa.String(length=36), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.String(length=64), nullable=True),
    sa.Column('error', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commands_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commands_state'), ['state'], unique=False)

    op.create_table('pots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=True),
    sa.Column('species_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('identify_confidence', sa.Float(), nullable=True),
    sa.Column('auto_water_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_water_threshold_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['plant_species.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', name='uq_pots_device_id')
    )
    with op.batch_alter_table('pots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pots_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pots_user_id'), ['user_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pot_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pot_id'], ['pots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_pot_id'), ['pot_id'], unique=False)

    op.create_table('care_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pot_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('volume_ml', sa.Float(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pot_id'], ['pots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('care_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_care_events_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_care_events_pot_id'), ['pot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('care_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_care_events_pot_id'))
        batch_op.drop_index(batch_op.f('ix_care_events_at'))

    op.drop_table('care_events')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_pot_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('pots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pots_user_id'))
        batch_op.drop_index(batch_op.f('ix_pots_device_id'))

    op.drop_table('pots')
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commands_state'))
        batch_op.drop_index(batch_op.f('ix_commands_device_id'))

    op.drop_table('commands')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_claimed_by'))
        batch_op.drop_index(batch_op.f('ix_devices_claim_code'))

    op.drop_table('devices')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_firebase_uid'))

    op.drop_table('users')
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.drop_index('ix_readings_device_time')

    op.drop_table('readings')
    with op.batch_alter_table('plant_species', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plant_species_scientific_name'))
        batch_op.drop_index(batch_op.f('ix_plant_species_plant_id_ref'))
        batch_op.drop_index(batch_op.f('ix_plant_species_genus'))

    op.drop_table('plant_species')
    # ### end Alembic commands ###
